spring:
  application:
    name: workspace
  profiles:
    active: dev
  datasource:
    hikari:
      pool-name: WorkspaceHikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,circuitbreakerevents
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      paymentGateway:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 50
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

app:
  jwt:
    expiration-minutes: 60
  email:
    welcome:
      subject: "¡Bienvenido a Workspace!"
      body: "Tu cuenta fue creada exitosamente."
    reservation-confirmed:
      subject: "Reserva confirmada"
      body: "Tu reserva fue confirmada exitosamente."
  payment:
    base-url: https://vk2mg.wiremockapi.cloud
    connect-timeout: 2s
    read-timeout: 3s
  reservation:
    max-advance-days: 15
    business-hours:
      monday-to-saturday:
        open-hour: 8
        close-hour: 20
      sunday:
        open-hour: 9
        close-hour: 19
