spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/workspace
    username: workspace
    password: workspace

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: debug
